---
- name: install packages
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: ufw already enabled
  command: ufw status verbose
  register: ufw_status_result
  changed_when: False

- name: open node_exporter port
  command: ufw allow 9100/tcp
  when:
    - not ufw_status_result.stdout is search("9100/tcp.*ALLOW IN.*Anywhere")

- name: open polkadot_metrics port
  command: ufw allow 9616/tcp
  when:
    - not ufw_status_result.stdout is search("9616/tcp.*ALLOW IN.*Anywhere")

- name: open p2p port
  command: ufw allow 30333/tcp
  when:
    - not ufw_status_result.stdout is search("30333/tcp.*ALLOW IN.*Anywhere")

- name: enable firewall
  shell: |
    set -o pipefail
    echo "y" | ufw enable
  args:
    executable: /bin/bash
  when: not ufw_status_result.stdout is search("Status.* active")
