---
- name: Add mina source
  shell: |
    echo "deb [trusted=yes] http://packages.o1test.net stretch stable" | sudo tee /etc/apt/sources.list.d/mina.list
  args:
    executable: /bin/bash
  changed_when: false

- name: install packages
  apt:
    name:
      - curl
      - unzip
      - mina-mainnet
      - mina-generate-keypair
    state: present
    update_cache: yes

- name: open 8302 port
  command: ufw allow 8302/tcp
  changed_when: false
