---
- name: 'Add nodejs apt key'
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: 'Add nodejs ppa for apt repo'
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ node_version }}.x {{ node_distribution }} main
    update_cache: yes

- name: 'Install nodejs'
  apt:
    update_cache: yes
    name: nodejs
    state: present

- name: Install mina monitor server
  shell: 'curl -s https://raw.githubusercontent.com/olton/scripts/master/mina/monitor/server/install.sh | bash -s'

- name: Move mina monitor
  copy:
    remote_src: true
    src: /home/{{ ansible_user }}/mina-monitor-server
    dest: /home/ubuntu
    owner: ubuntu
    group: ubuntu

- name: Make config file
  template:
    src: config.json.j2
    dest: /home/ubuntu/mina-monitor-server/config.json
    owner: ubuntu
    group: ubuntu

- name: create minamon systemd unit
  copy:
    src: minamon.service
    dest: /etc/systemd/system/minamon.service
    owner: root
    group: root
    mode: '600'

- name: start minamon service
  systemd:
    name: minamon
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
