---
- name: register public ip
  uri:
    url: https://api.ipify.org?format=json
  register: public_ip

- name: create .mina-env file
  template:
    src: mina-env.j2
    dest: /home/ubuntu/.mina-env
    owner: ubuntu
    group: ubuntu
    mode: '0664'

- name: create .mina-config directory
  file:
    path: /home/ubuntu/.mina-config
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0775'

- name: create /.mina-config/daemon.json file
  template:
    src: daemon.json.j2
    dest: /home/ubuntu/.mina-config/daemon.json
    owner: ubuntu
    group: ubuntu
    mode: '0664'

- name: Run Daemon
  remote_user: ubuntu
  shell: |
    systemctl --user daemon-reload
    systemctl --user stop mina
    systemctl --user start mina
    systemctl --user enable mina
    sudo loginctl enable-linger
  args:
    executable: /bin/bash
  changed_when: false

- name: install packages
  apt:
    name:
      - mina-bp-stats-sidecar
    state: present
    update_cache: yes

- name: update sidecar file
  template:
    src: mina-sidecar.json.j2
    dest: /etc/mina-sidecar.json
    owner: root
    group: root
    mode: '0644'

- name: Enable sidecar service
  systemd:
    name: mina-bp-stats-sidecar
    state: started
    enabled: yes
